### ISSUE TITLE
AssertionError: Wrong current data

### ISSUE THREAD

**Issue by DKorytkin** [DKorytkin/Checker#21]
```python
ex = {'caption': basestring,
 'data': Or(({'max': Or((<type 'int'>, None)), 'min': Or((<type 'int'>, None)), OptionalKey(presets): [<type 'int'>]}, {'values': [{'count': <type 'int'>, 'caption': <type 'basestring'>, 'id': Or((<type 'int'>, <type 'basestring'>))}]})),
 'key': basestring}
```
```python
cu = [{'caption': 'price', 'data': {'max': None, 'min': None}, 'key': 'price'},
 {'caption': 'state',
  'data': {'values': [{'caption': 'ru', 'count': 23, 'id': 1123},
    {'caption': 'fr', 'count': 21, 'id': 666}]},
  'key': 'bss1'}]


```
```python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-65e138aa7423>", line 53, in <module>
    u'key': u'bss1'}])
  File "/home/dkorytkin/json_checker/checker.py", line 325, in validate
    result = checker.validate(data)
  File "/home/dkorytkin/json_checker/checker.py", line 258, in validate
    result = list_checker.validate(data)
  File "/home/dkorytkin/json_checker/checker.py", line 102, in validate
    result = checker.validate(data)
  File "/home/dkorytkin/json_checker/checker.py", line 266, in validate
    self._append_errors(dict_checker.validate(data))
  File "/home/dkorytkin/json_checker/checker.py", line 157, in validate
    result = checker.validate(current_value)
  File "/home/dkorytkin/json_checker/checker.py", line 268, in validate
    result = self.expected_data.validate(data)
  File "/home/dkorytkin/json_checker/checker.py", line 202, in validate
    res = checker.validate(current_data)
  File "/home/dkorytkin/json_checker/checker.py", line 266, in validate
    self._append_errors(dict_checker.validate(data))
  File "/home/dkorytkin/json_checker/checker.py", line 157, in validate
    result = checker.validate(current_value)
  File "/home/dkorytkin/json_checker/checker.py", line 256, in validate
    assert data and _is_iter(data), 'Wrong current data'
AssertionError: Wrong current data
```

**Comment by DKorytkin** [comment]
```python
from checker import Checker, Or, And, OptionalKey
ex = {'caption': basestring,
 'data': Or({'max': Or(int, None), 'min': Or(int, None), OptionalKey('presets'): [int]}, {'values': [{'count': int, 'caption': basestring, 'id': Or(int, basestring)}]}),
 'key': basestring}
cu = [{'caption': 'price', 'data': {'max': None, 'min': None}, 'key': 'price'},
 {'caption': 'state',
  'data': {'values': [{'caption': 'ru', 'count': 23, 'id': 1123},
    {'caption': 'fr', 'count': 21, 'id': 666}]},
  'key': 'bss1'}]
Checker(ex).validate(cu)

```

**Comment by DKorytkin** [comment]
not bug
