### ISSUE TITLE
TypeError: sequence item 1: expected string, NoneType found

### ISSUE THREAD

**Issue by DKorytkin** [DKorytkin/Checker#22]
```python
from checker import Checker, Or, And, OptionalKey
import requests
ex = [{'caption': basestring,
 'data': Or(
     {'max': Or(int, None), 'min': Or(int, None), OptionalKey('presets'): [int]}, 
     {'values': [{'count': int, 'caption': basestring, 'id': Or(int, basestring)}]}),
 'key': basestring}]
cu = [
    {'caption': 'price', 'data': {'max': 'None', 'min': None}, 'key': 'price'},
    {'caption': 'state', 'data': {'values': [{'caption': 'ru', 'count': 23, 'id': 1123},
    {'caption': 'fr', 'count': 21, 'id': 666}]},
  'key': 'bss1'}]
Checker(ex).validate(cu)

```

```python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-4644120212cb>", line 16, in <module>
    Checker(ex).validate(cu)
  File "/home/dkorytkin/json_checker/checker.py", line 323, in validate
    result = checker.validate(data)
  File "/home/dkorytkin/json_checker/checker.py", line 256, in validate
    result = list_checker.validate(data)
  File "/home/dkorytkin/json_checker/checker.py", line 100, in validate
    result = checker.validate(data)
  File "/home/dkorytkin/json_checker/checker.py", line 264, in validate
    self._append_errors(dict_checker.validate(data))
  File "/home/dkorytkin/json_checker/checker.py", line 154, in validate
    result = checker.validate(current_value)
  File "/home/dkorytkin/json_checker/checker.py", line 266, in validate
    result = self.expected_data.validate(data)
  File "/home/dkorytkin/json_checker/checker.py", line 205, in validate
    return self._format_errors(errors)
  File "/home/dkorytkin/json_checker/checker.py", line 192, in _format_errors
    self._format_data(),
  File "/home/dkorytkin/json_checker/checker.py", line 187, in _format_data
    return tuple(_format_data(d) for d in self.expected_data)
  File "/home/dkorytkin/json_checker/checker.py", line 187, in <genexpr>
    return tuple(_format_data(d) for d in self.expected_data)
  File "/home/dkorytkin/json_checker/checker.py", line 65, in _format_data
    return json.dumps(data)
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
  File "/home/dkorytkin/json_checker/checker.py", line 183, in __repr__
    data=', '.join(self._format_data())
TypeError: sequence item 1: expected string, NoneType found

```

**Comment by DKorytkin** [comment]
fixed
```python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-4a75addf75aa>", line 13, in <module>
    Checker(ex).validate(cu)
  File "/home/dkorytkin/json_checker/checker.py", line 310, in validate
    result = checker.validate(data)
  File "/home/dkorytkin/json_checker/checker.py", line 246, in validate
    return list_checker.validate(data)
  File "/home/dkorytkin/json_checker/checker.py", line 99, in validate
    result = checker.validate(data)
  File "/home/dkorytkin/json_checker/checker.py", line 253, in validate
    return dict_checker.validate(data)
  File "/home/dkorytkin/json_checker/checker.py", line 157, in validate
    self._append_errors_or_raise(key, result)
  File "/home/dkorytkin/json_checker/checker.py", line 140, in _append_errors_or_raise
    raise DictCheckerError(DICT_ERROR_TEMPLATE.format(key, result))
DictCheckerError: 
From key="data":
	Not valid data Or("{'max': Or(<type 'int'>, None), OptionalKey(presets): [<type 'int'>], 'min': Or(<type 'int'>, None)}", "{'values': [{'count': <type 'int'>, 'caption': <type 'basestring'>, 'id': Or(<type 'int'>, <type 'basestring'>)}]}")

```

**Comment by DKorytkin** [comment]
implimented in #23
