### ISSUE TITLE
not correct work operator Or

### ISSUE THREAD

**Issue by DKorytkin** [DKorytkin/Checker#23]
```python
from checker import Checker, Or, OptionalKey
ex = [
    {'caption': basestring,  'data': Or(
         {'max': Or(int, None), 'min': Or(int, None), OptionalKey('presets'): [int]}, 
         {'values': [
                {'count': int, 'caption': basestring, 'id': Or(int, basestring)}
         ]
     }),  'key': basestring}]

cu = [
    {'caption': 'price', 'data': {'max': None, 'min': None}, 'key': 'price'},
    {'caption': 'state',  'data': {'values': [
         {'caption': 'ru', 'count': 23, 'id': 1123},
         {'caption': 122, 'count': 21, 'id': 666}]},
    'key': 'bss1'}
]

Checker(ex).validate(cu)

```

```python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-3f95426b5a59>", line 1, in <module>
    Checker(ex, ignore_extra_keys=True).validate(cu)
  File "/home/dkorytkin/json_checker/checker.py", line 326, in validate
    result = checker.validate(data)
  File "/home/dkorytkin/json_checker/checker.py", line 261, in validate
    return list_checker.validate(data)
  File "/home/dkorytkin/json_checker/checker.py", line 102, in validate
    result = checker.validate(data)
  File "/home/dkorytkin/json_checker/checker.py", line 268, in validate
    return dict_checker.validate(data)
  File "/home/dkorytkin/json_checker/checker.py", line 160, in validate
    self._append_errors_or_raise(key, result)
  File "/home/dkorytkin/json_checker/checker.py", line 143, in _append_errors_or_raise
    raise DictCheckerError(DICT_ERROR_TEMPLATE.format(key, result))
DictCheckerError: 
From key="data"
	Not valid data Or("{'max': Or(<type 'int'>, None), OptionalKey(presets): [<type 'int'>], 'min': Or(<type 'int'>, None)}", "{'values': [{'count': <type 'int'>, 'caption': <type 'basestring'>, 'id': Or(<type 'int'>, <type 'basestring'>)}]}")
	DictCheckerErrors:
Missing keys: max, values, min
	DictCheckerErrors:
From key="values"
	ListCheckerErrors:
DictCheckerErrors:
From key="caption"
	current value 122 is not basestring

```

**Comment by DKorytkin** [comment]
need implemented correct error message

**Comment by DKorytkin** [comment]
fixed, need tested
